version: '3.8'

x-log-rotation: &log-rotation
  # driver: "json-file"
  options:
    max-size: "200k"
    max-file: "3"

x-container-ulimits: &container-ulimits
  nproc: 20000
  nofile:
    soft: 10000
    hard: 20000


services:
  # ================================rest API service===================================
  restapi:
    image: cgain:dev
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: ./build/Dockerfile
    restart: on-failure
    environment:
      - API_KEY
      - SECRET_KEY
      - API_PREFIX
      - API_V1_STR
      - PROJECT_NAME
    logging:
      <<: *log-rotation
    command: pipenv run python src/main.py
    # command: /bin/sleep 2000
    healthcheck:
      test: "curl --fail http://localhost:8000${API_PREFIX}/docs || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s     

